import Link from "next/link";
import { redirect } from "next/navigation";
import { getReportBundle } from "@/lib/data";
import { getSessionUser } from "@/lib/auth";
import { PrintButton } from "@/app/components/PrintButton";
import { SECTION_KEYS, SECTION_LABELS, type SectionKey } from "@/lib/db/types";
import { money, signedMoney, formatDateTime, flagTypeLabel } from "@/lib/format";
import type { ReportOutput } from "@/lib/db/types";

export const dynamic = "force-dynamic";

function section(o: ReportOutput, k: SectionKey): string {
  return (o[k] as string | null) ?? "";
}

export default async function PrintPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const user = await getSessionUser();
  if (!user) redirect("/login");
  const bundle = await getReportBundle(id);
  if (!bundle || bundle.report.user_id !== user.id) return <div className="p-8">Report not available.</div>;

  const { report, forecastWeeks, flags, output } = bundle;
  const activeFlags = flags.filter((f) => f.review_status !== "dismissed");

  return (
    <main className="mx-auto max-w-3xl bg-white px-8 py-10 text-neutral-900">
      <div className="mb-6 flex items-center justify-between no-print">
        <Link href={`/report/${id}`} className="text-sm font-medium text-neutral-500 hover:text-neutral-800">
          ← Back to report
        </Link>
        <PrintButton />
      </div>

      <header className="mb-6 border-b border-neutral-300 pb-4">
        <h1 className="text-2xl font-bold">Weekly Cash Flow Report</h1>
        <p className="text-neutral-600">{report.week_label}</p>
        <p className="mt-1 text-sm">
          Status:{" "}
          <span className={report.status === "approved" ? "font-semibold text-emerald-700" : "font-semibold text-amber-700"}>
            {report.status}
          </span>
          {output?.approved_at && <> · Approved {formatDateTime(output.approved_at)}</>}
        </p>
      </header>

      <section className="mb-6">
        <h2 className="mb-2 text-sm font-semibold uppercase tracking-wide text-neutral-500">4-Week Rolling Forecast</h2>
        <table className="w-full border-collapse text-sm">
          <thead>
            <tr className="border-b border-neutral-300 text-left">
              <th className="py-2">Week</th>
              <th className="py-2 text-right">Opening</th>
              <th className="py-2 text-right">Inflows</th>
              <th className="py-2 text-right">Outflows</th>
              <th className="py-2 text-right">Closing</th>
              <th className="py-2 text-right">Forecast</th>
              <th className="py-2 text-right">Variance</th>
            </tr>
          </thead>
          <tbody>
            {forecastWeeks.map((w) => (
              <tr key={w.week_offset} className="border-b border-neutral-200">
                <td className="py-1.5">{w.week_label}</td>
                <td className="py-1.5 text-right tabular-nums">{money(w.opening_balance)}</td>
                <td className="py-1.5 text-right tabular-nums">{money(w.total_inflows)}</td>
                <td className="py-1.5 text-right tabular-nums">{money(w.total_outflows)}</td>
                <td className="py-1.5 text-right font-semibold tabular-nums">{money(w.closing_balance)}</td>
                <td className="py-1.5 text-right tabular-nums text-neutral-500">{money(w.forecast_closing_balance)}</td>
                <td className="py-1.5 text-right tabular-nums">{signedMoney(w.closing_balance - w.forecast_closing_balance)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      {output &&
        SECTION_KEYS.map((k) => (
          <section key={k} className="mb-5">
            <h2 className="mb-1 text-sm font-semibold uppercase tracking-wide text-neutral-500">{SECTION_LABELS[k]}</h2>
            <p className="whitespace-pre-line text-sm leading-relaxed">{section(output, k) || "—"}</p>
          </section>
        ))}

      <section className="mb-6">
        <h2 className="mb-2 text-sm font-semibold uppercase tracking-wide text-neutral-500">
          Active Risk Flags ({activeFlags.length})
        </h2>
        <ul className="space-y-2 text-sm">
          {activeFlags.map((f) => (
            <li key={f.id} className="border-l-2 border-neutral-300 pl-3">
              <span className="font-semibold uppercase">{f.severity}</span> · {flagTypeLabel(f.flag_type)} — {f.description}
              {f.recommended_action && <div className="text-neutral-600">→ {f.recommended_action}</div>}
            </li>
          ))}
          {activeFlags.length === 0 && <li className="text-neutral-500">No active risks.</li>}
        </ul>
      </section>

      <footer className="mt-8 border-t border-neutral-300 pt-3 text-xs text-neutral-400">
        Generated by AI-Assisted Weekly Cash Flow Reporting.
      </footer>
    </main>
  );
}
